[versions]
javapoet = "1.13.0"
hilt = "2.51"
agp = "8.8.0"
kotlin = "1.9.23"
ksp = "1.9.23-1.0.20"

junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.5.1"
appcompat = "1.7.0"
material = "1.12.0"
coreKtx = "1.12.1"
activityCompose = "1.8.2"
composeBom = "2024.04.01"
foundationLayoutAndroid = "1.7.2"
preferenceKtx = "1.2.1"
room = "2.6.1"
roomCommonJvm = "2.7.1"
navigationFragment = "2.8.8"
navigationUi = "2.9.0"
navigationCompose = "2.8.8"
coilCompose = "2.6.0"
gson = "2.10.1"

[libraries]
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }
# Kotlin & Android Core
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
material3 = { group = "androidx.compose.material3", name = "material3" }
foundation-layout-android = { group = "androidx.compose.foundation", name = "foundation-layout-android", version.ref = "foundationLayoutAndroid" }

# Activity & Navigation
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragment" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-common-jvm = { group = "androidx.room", name = "room-common", version.ref = "roomCommonJvm" }

# Gson
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# Coil
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }

# Preferences
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }

# Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }